# web访问端口号  约定8088
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

# 配置数据源信息
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource  # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: space5213
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），默认30s，超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
  servlet: #上传文件大小配置
    multipart:
      max-file-size: 10MB #设置单个文件的大小
      max-request-size: 100MB #设置单次请求文件的总大小
  redis:
    password: space5213
    database: 1
    #本地虚拟机IP
    host: 192.168.194.2
    port: 6379

# mybatis 配置
mybatis:
  type-aliases-package: com.imooc.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志sql打印在控制台
# mybatis mapper 配置
# 通用 Mapper 配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false  #在进行数据库操作时，判断 name！= null，是否追加name != ''
  identity: MYSQL

# 自定义日志路径配置
logback:
  logdir: /Users/dlwlrmaone/logs/foodie_log

#分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

#定时任务配置
autoCloseOrder:
  task:
    timerTask: "0 0 0/1 * * ?"